### ISSUE TITLE
Codestyle conventions

### ISSUE THREAD

**Issue by thejOK3r** [biakaveron/debug-toolbar#11]
Hi there,

it would be nice if this module would be conform to the kohana codestyle conventions because my jenkins shows me more than 500 warnings. Especially the firephp.php is a problem. And if i do it all changes will be gone on the next update.
What do you think?

Cheers
Chris

**Comment by smgladkovskiy** [comment]
@thejOK3r: what branch do you use? In 3.1 firephp is used as a submodule and does not belong to debugtoolbar module...

**Comment by thejOK3r** [comment]
Ah, i see. I will try the 3.1 branch. I still have the 3.0. If there are still so many warnings i will try to contact the firephp developers.
Thanks so far ;-)
