### ISSUE TITLE
Баг в рендере

### ISSUE THREAD

**Issue by alexkuznetsov** [biakaveron/debug-toolbar#20]
панель не должна отрисовываться, если выполнение прервано с bootstrap.php. Т.е., если запрос еще не создан.

[Вот тут](https://github.com/biakaveron/debug-toolbar/blob/3.3/classes/Kohana/Debugtoolbar.php#L434) необходимо добавить вот это: 

`if (Request::initial() == NULL OR Request::initial()->is_ajax())`

Думаю должно помочь.

**Comment by biakaveron** [comment]
А в каких случаях такое возможно? Когда идет обработка исключения? По идее, в этом случае все равно надо создавать запрос...

**Comment by alexkuznetsov** [comment]
Это случится если произойдет исключение (ошибка) в файле bootstrap.php. К примеру, не найдена директория кэша/логов или я такой паразит и сам что-то решил проверить и остновил выполнение простым die/exit. В конце bootstrap.php сделайте 
`exit(print_r($something, TRUE));`
и панелька отвалится с исключением, так как она уже зарегистрировала свой обработчик на завершение. Но, Request еще не создан, он создается после того как обрабатывается bootstrap.php
