### ISSUE TITLE
Ошибка вывода при mime != html

### ISSUE THREAD

**Issue by alexkuznetsov** [biakaveron/debug-toolbar#21]
Собственно ошибка в том, что панель выводится во всех случаях, не учитывая mime контента.
Это не правильно на мой взгляд. Предлагаю следующее возможное решение в лоб:

В `DebugToolbar::is_enabled` после проверки что запрос не пустой и не ajax добавляем проверку mime контента.

Что-то типа такого:

```
$all_headers = headers_list();

foreach($all_headers as $header)
{
    list($key, $value) = explode(': ',$header);
    if (strcasecmp('content-type', $key) == 0 AND strcasecmp('text/html', $value) != 0)
    {
        return FALSE;
    }
}
```

Панель нам нужна только при просмотре html страниц, соответственно для всех других страниц/типов ответа она должна блокироваться.

Если найдется более удобное решение то неплохо было бы на него посмотреть.

**Comment by biakaveron** [comment]
Не думаю, что надо обязательно на Mime рассчитывать. Есть такой вариант, я его в своем модуле Message применяю:

```
//  в is_enabled()
if (in_array(Route::name(Request::initial()->route()), Arr::get($config, 'ignored_routes', array())))
{
    return FALSE;
}
```

То есть просто в конфиге объявляем маршруты, для которых панелька не должна показываться. Можно дополнительно еще метод `ignore_route($route)` добавить.

**Comment by alexkuznetsov** [comment]
Все это замечательно, если несколько маршрутов.
Но! Если у меня один стандартный маршрут, то встает проблема выноса всех сервисных экшенов в отдельный(-е) маршрут(-ы) что не самый лучший вариант. 
А здесь же проблема решается вполне быстро и без особых затрат. 
У вас есть котроллер Welcome который расширен от базового Base.
Bаse дает нам скажем метод `send_json`, кидающий json-строку в ответ. Получается чтобы из экшена Welcome погадить json-ом придется сделать дополнительный маршрут, который проигнорирует DebugToolbar и не отрисуется? :fearful: 
Это не самый удобный вариант.

Тогда уже удобнее добавить что-то типа интерфейса RenderBehavior, опциональное поле конфигурации render_behavior которое отвечает за класс дополнительной проверки вывода.

Если пользователь в конфиге втыкает класс, наследуемый от данного интерфейса, то DT может запросить дополнительную проверку на вывод уже из _класса пользователя_, где уже извращаются люди кто на что горазд.

Последний вариант попахивает гибкостью и, отчасти, усложнением. Но, он дает ~~кучу геммороев от кривых рук~~ некоторую свободу конечному пользователю и, надеюсь меньше писанины.

**Comment by biakaveron** [comment]
А почему бы просто не сделать метод DebugToolbar::disable($disable = TRUE)? В контроллере ведь заранее известно, какой тип данных будет отдаваться и тд.

**Comment by alexkuznetsov** [comment]
Ну, в принципе это тоже вариант. 
Дело вкуса конечно. 

Чем же так плох первый вариант? 

Я не вижу особых проблем в его использовании - данных код позволит раз и навсегда ограничить вывод панели без дополнительных костылей в других компонентах приложения. 

Или я не замечаю всей картины в целом, есть какие-то скрытые камни?

**Comment by biakaveron** [comment]
Хотя бы потому, что проще и надежнее )) Как вариант, можно дизейблить DebugToolbar из Controller_Template::after(). Так будет удобнее, потому что имеется $this->request->response() с более удобными методами для обработки заголовков.

**Comment by alexkuznetsov** [comment]
Ну на счет надежности и простоты я бы поспорил :-P
В момент рендера заголовки отправлены уже, отсутствие удобств (я про $this->request->response()) - это не такая крупная проблема.

Просто я рассуждаю со стороны ленивого пользователя, который будет всегда забывать про то что нужно бы вырубить отрисовку панели. 

Или же дать пользователю самому контролировать вывод панели. 
До есть запускать ручками DebugToolbar::render. 
Я так и делал раньше, как то проблем не было.

**Comment by biakaveron** [comment]
Кстати, как вариант... Сделать опцию auto_render в конфиге ))

**Comment by alexkuznetsov** [comment]
Да, тоже вариант!

**Comment by biakaveron** [comment]
Тогда подведу итог:
1. Делаю опцию auto_render в конфиге, в зависимости от нее регистрирую обработчик для shutdown.
2. На всякий случай добавлю метод disable() для ручного управления видимостью панельки.

Более сложные варианты типа анализа MIME можно превратить в код контроллера + вызов Debugtoolbar::disable().

**Comment by alexkuznetsov** [comment]
Отлично!

**Comment by biakaveron** [comment]
Опция auto_render в конфиге уже присутствует, добавил методы enable() и disable(). По умолчанию тулбар всегда разрешен.
