### ISSUE TITLE
Debug Toolbar not AutoRendering

### ISSUE THREAD

**Issue by marcelorodrigo** [biakaveron/debug-toolbar#3]
Auto_render = true option does not display the toolbar in the debug interface, but via Firebug can view information on the toolbar.

But when the auto_render = false toolbar displays correctly.
Always IN_PRODUCTION = false in my development environment
There should be the opposite?

**Comment by marcelorodrigo** [comment]
Anyway IN_PRODUCTION=true and auto_render=false always display debug-toolbar in interface.

**Comment by biakaveron** [comment]
Works for me (3.2 and 3.3 branches).
